// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCasbinRule = "casbin_rules"

// CasbinRule mapped from table <casbin_rules>
type CasbinRule struct {
	ID    int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Ptype string `gorm:"column:ptype;not null" json:"ptype"`
	V0    string `gorm:"column:v0;not null" json:"v0"`
	V1    string `gorm:"column:v1;not null" json:"v1"`
	V2    string `gorm:"column:v2;not null" json:"v2"`
	V3    string `gorm:"column:v3;not null" json:"v3"`
	V4    string `gorm:"column:v4;not null" json:"v4"`
	V5    string `gorm:"column:v5;not null" json:"v5"`
}

// TableName CasbinRule's table name
func (*CasbinRule) TableName() string {
	return TableNameCasbinRule
}
