// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/datatypes"
	"gorm.io/plugin/soft_delete"
)

const TableNameHTTPRequestLog = "http_request_log"

// HTTPRequestLog mapped from table <http_request_log>
type HTTPRequestLog struct {
	ID            int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                   // ID
	Method        string                `gorm:"column:method;default:GET;comment:请求方式" json:"method"`                           // 请求方式
	URL           string                `gorm:"column:url;comment:请求 url" json:"url"`                                           // 请求 url
	Params        string                `gorm:"column:params;comment:请求参数 (query/body)" json:"params"`                          // 请求参数 (query/body)
	Result        datatypes.JSON        `gorm:"column:result;comment:返回内容" json:"result"`                                       // 返回内容
	Device        string                `gorm:"column:device;comment:设备：chrome||xxx, android, ios, mac, windows" json:"device"` // 设备：chrome||xxx, android, ios, mac, windows
	DeviceVersion string                `gorm:"column:device_version;comment:设备版本号" json:"device_version"`                      // 设备版本号
	Os            string                `gorm:"column:os;comment:操作系统" json:"os"`                                               // 操作系统
	OsVersion     string                `gorm:"column:os_version;comment:系统版本号" json:"os_version"`                              // 系统版本号
	IP            string                `gorm:"column:ip;comment:ip" json:"ip"`                                                 // ip
	UserPid       int64                 `gorm:"column:user_pid;comment:用户主 ID" json:"user_pid"`                                 // 用户主 ID
	UserID        int64                 `gorm:"column:user_id;comment:用户 ID" json:"user_id"`                                    // 用户 ID
	UserType      string                `gorm:"column:user_type;comment:用户类型" json:"user_type"`                                 // 用户类型
	CreateTime    int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`         // 创建时间
	Delete_       soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                      // 删除状态:0 未删除，1 已删除
}

// TableName HTTPRequestLog's table name
func (*HTTPRequestLog) TableName() string {
	return TableNameHTTPRequestLog
}
