// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/datatypes"
	"gorm.io/plugin/soft_delete"
)

const TableNamePayOrderLog = "pay_order_log"

// PayOrderLog mapped from table <pay_order_log>
type PayOrderLog struct {
	ID              int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`             // ID
	UUID            string                `gorm:"column:uuid;not null;comment:全链路唯一标记" json:"uuid"`                         // 全链路唯一标记
	OrderNo         string                `gorm:"column:order_no;not null;comment:交易订单号" json:"order_no"`                   // 交易订单号
	MerchantOrderNo string                `gorm:"column:merchant_order_no;not null;comment:商户订单号" json:"merchant_order_no"` // 商户订单号
	ChannelOrderNo  string                `gorm:"column:channel_order_no;not null;comment:渠道订单号" json:"channel_order_no"`   // 渠道订单号
	Req             datatypes.JSON        `gorm:"column:req;comment:请求内容" json:"req"`                                       // 请求内容
	Res             datatypes.JSON        `gorm:"column:res;comment:返回内容" json:"res"`                                       // 返回内容
	Process         datatypes.JSON        `gorm:"column:process;comment:已完成进程" json:"process"`                              // 已完成进程
	Timing          string                `gorm:"column:timing;not null;comment:订单耗时 毫秒" json:"timing"`                     // 订单耗时 毫秒
	CreateTime      int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`   // 创建时间
	UpdateTime      int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"`   // 更新时间
	Delete_         soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                // 删除状态:0 未删除，1 已删除
}

// TableName PayOrderLog's table name
func (*PayOrderLog) TableName() string {
	return TableNamePayOrderLog
}
