// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNamePayMerchantRiskcontrol = "pay_merchant_riskcontrol"

// PayMerchantRiskcontrol mapped from table <pay_merchant_riskcontrol>
type PayMerchantRiskcontrol struct {
	ID               int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                                    // ID
	MerchantID       int64                 `gorm:"column:merchant_id;not null;comment:商户 id" json:"merchant_id"`                                    // 商户 id
	StartTime        string                `gorm:"column:start_time;not null;comment:开始时间" json:"start_time"`                                       // 开始时间
	EndTime          string                `gorm:"column:end_time;not null;comment:结束时间" json:"end_time"`                                           // 结束时间
	InUnitMinAmount  float64               `gorm:"column:in_unit_min_amount;not null;default:0.00;comment:入款_单笔最小交易金额" json:"in_unit_min_amount"`   // 入款_单笔最小交易金额
	InUnitMaxAmount  float64               `gorm:"column:in_unit_max_amount;not null;default:0.00;comment:入款_单笔最大交易金额" json:"in_unit_max_amount"`   // 入款_单笔最大交易金额
	InDayMaxAmount   float64               `gorm:"column:in_day_max_amount;not null;default:0.00;comment:入款_单日最大交易金额" json:"in_day_max_amount"`     // 入款_单日最大交易金额
	OutUnitMinAmount float64               `gorm:"column:out_unit_min_amount;not null;default:0.00;comment:出款_单笔最小交易金额" json:"out_unit_min_amount"` // 出款_单笔最小交易金额
	OutUnitMaxAmount float64               `gorm:"column:out_unit_max_amount;not null;default:0.00;comment:出款_单笔最大交易金额" json:"out_unit_max_amount"` // 出款_单笔最大交易金额
	OutDayMaxAmount  float64               `gorm:"column:out_day_max_amount;not null;default:0.00;comment:出款_单日最大交易金额" json:"out_day_max_amount"`   // 出款_单日最大交易金额
	Status           int64                 `gorm:"column:status;not null;default:1;comment:状态:1 启用，2 关闭" json:"status"`                             // 状态:1 启用，2 关闭
	IsSystem         int64                 `gorm:"column:is_system;not null;comment:是否系统设置:1 是，0 不是" json:"is_system"`                              // 是否系统设置:1 是，0 不是
	CreateTime       int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`                          // 创建时间
	UpdateTime       int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"`                          // 更新时间
	Delete_          soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                                       // 删除状态:0 未删除，1 已删除
	OutConfirmAmount float64               `gorm:"column:out_confirm_amount;not null;default:0.00;comment:出款二次确认最小交易金额" json:"out_confirm_amount"`  // 出款二次确认最小交易金额
	InConfirmAmount  float64               `gorm:"column:in_confirm_amount;not null;default:0.00;comment:入款提醒最小交易金额" json:"in_confirm_amount"`      // 入款提醒最小交易金额
}

// TableName PayMerchantRiskcontrol's table name
func (*PayMerchantRiskcontrol) TableName() string {
	return TableNamePayMerchantRiskcontrol
}
