// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNamePayAgent = "pay_agent"

// PayAgent mapped from table <pay_agent>
type PayAgent struct {
	ID         int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                      // ID
	Pid        int64                 `gorm:"column:pid;comment:推荐人" json:"pid"`                                                 // 推荐人
	MasterID   int64                 `gorm:"column:master_id;comment:主 ID" json:"master_id"`                                    // 主 ID
	Username   string                `gorm:"column:username;not null;comment:用户名" json:"username"`                              // 用户名
	Nickname   string                `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`                               // 昵称
	Password   string                `gorm:"column:password;not null;comment:密码" json:"password"`                               // 密码
	Invitecode string                `gorm:"column:invitecode;not null;comment:邀请码" json:"invitecode"`                          // 邀请码
	Alias_     string                `gorm:"column:alias;not null;comment:别名" json:"alias"`                                     // 别名
	Phone      string                `gorm:"column:phone;not null;comment:手机号" json:"phone"`                                    // 手机号
	Email      string                `gorm:"column:email;not null;comment:电子邮箱" json:"email"`                                   // 电子邮箱
	Hashcode   string                `gorm:"column:hashcode;not null;comment:唯一标识符" json:"hashcode"`                            // 唯一标识符
	SubSuffix  string                `gorm:"column:sub_suffix;not null;comment:域名前缀" json:"sub_suffix"`                         // 域名前缀
	Avatar     string                `gorm:"column:avatar;comment:头像" json:"avatar"`                                            // 头像
	Status     int64                 `gorm:"column:status;not null;default:1;comment:帐号状态:1 启用，2 停用" json:"status"`             // 帐号状态:1 启用，2 停用
	Remark     string                `gorm:"column:remark;not null;comment:备注" json:"remark"`                                   // 备注
	Roles      string                `gorm:"column:roles;not null;comment:角色 ID 拼接字符串" json:"roles"`                            // 角色 ID 拼接字符串
	Token      string                `gorm:"column:token;not null;comment:用户鉴权字符串" json:"token"`                                // 用户鉴权字符串
	F2a        string                `gorm:"column:f2a;not null;comment:用户二次认证" json:"f2a"`                                     // 用户二次认证
	F2aEnable  int64                 `gorm:"column:f2a_enable;not null;default:2;comment:二次认证强制开启:1 启用，2 禁用" json:"f2a_enable"` // 二次认证强制开启:1 启用，2 禁用
	CreateTime int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`            // 创建时间
	UpdateTime int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"`            // 更新时间
	Delete_    soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                         // 删除状态:0 未删除，1 已删除
	ErrorCount int64                 `gorm:"column:error_count;not null;comment:错误次数" json:"error_count"`                       // 错误次数
}

// TableName PayAgent's table name
func (*PayAgent) TableName() string {
	return TableNamePayAgent
}
