// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNamePayProductCharge = "pay_product_charge"

// PayProductCharge mapped from table <pay_product_charge>
type PayProductCharge struct {
	ID          int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                   // ID
	ProductID   int64                 `gorm:"column:product_id;not null;comment:支付产品 id" json:"product_id"`                   // 支付产品 id
	ChannelRate float64               `gorm:"column:channel_rate;not null;default:0.000000;comment:渠道费率" json:"channel_rate"` // 渠道费率
	TradeRate   float64               `gorm:"column:trade_rate;not null;default:0.000000;comment:商户费率" json:"trade_rate"`     // 商户费率
	Status      int64                 `gorm:"column:status;not null;default:1;comment:状态:1 启用，2 关闭" json:"status"`            // 状态:1 启用，2 关闭
	IsSystem    int64                 `gorm:"column:is_system;not null;comment:是否系统设置:1 是，0 不是" json:"is_system"`             // 是否系统设置:1 是，0 不是
	CreateTime  int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`         // 创建时间
	UpdateTime  int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"`         // 更新时间
	Delete_     soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                      // 删除状态:0 未删除，1 已删除
}

// TableName PayProductCharge's table name
func (*PayProductCharge) TableName() string {
	return TableNamePayProductCharge
}
