// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNamePayProductAccount = "pay_product_account"

// PayProductAccount mapped from table <pay_product_account>
type PayProductAccount struct {
	ID         int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`             // ID
	ProductID  int64                 `gorm:"column:product_id;not null;comment:支付产品 id" json:"product_id"`             // 支付产品 id
	Name       string                `gorm:"column:name;not null;comment:子账号名称" json:"name"`                           // 子账号名称
	Params     string                `gorm:"column:params;not null;comment:自定义配置参数" json:"params"`                     // 自定义配置参数
	Weight     int64                 `gorm:"column:weight;not null;comment:权重值" json:"weight"`                         // 权重值
	Tags       string                `gorm:"column:tags;not null;comment:标签，多个用英文逗号分隔" json:"tags"`                    // 标签，多个用英文逗号分隔
	Status     int64                 `gorm:"column:status;not null;default:1;comment:状态:1 启用，2 关闭，3 异常" json:"status"` // 状态:1 启用，2 关闭，3 异常
	Remark     string                `gorm:"column:remark;not null;comment:备注" json:"remark"`                          // 备注
	CreateTime int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`   // 创建时间
	UpdateTime int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"`   // 更新时间
	Delete_    soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                // 删除状态:0 未删除，1 已删除
	Type       int64                 `gorm:"column:type;not null;comment:类型:1 代收，2 代付" json:"type"`                    // 类型:1 代收，2 代付
	Code       string                `gorm:"column:code;not null;comment:产品编码" json:"code"`                            // 产品编码
	Cache      int64                 `gorm:"column:cache;not null;default:1;comment:缓存订单:1 启用，0 关闭" json:"cache"`      // 缓存订单:1 启用，0 关闭
}

// TableName PayProductAccount's table name
func (*PayProductAccount) TableName() string {
	return TableNamePayProductAccount
}
