// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNamePayExportTask = "pay_export_task"

// PayExportTask mapped from table <pay_export_task>
type PayExportTask struct {
	ID           int64                 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreateTime   int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`              // 创建日期
	UpdateTime   int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"`              // 修改日期
	CreatorID    int64                 `gorm:"column:creator_id;not null;comment:导出人的 ID" json:"creator_id"`                        // 导出人的 ID
	CreatorType  string                `gorm:"column:creator_type;not null;comment:用户类型, admin|agent|merchant" json:"creator_type"` // 用户类型, admin|agent|merchant
	Type         int64                 `gorm:"column:type;not null;comment:类型：由代码层定义" json:"type"`                                  // 类型：由代码层定义
	Status       int64                 `gorm:"column:status;not null;comment:状态, 1: 正在导出, 2: 导出成功,3: 导出失败" json:"status"`           // 状态, 1: 正在导出, 2: 导出成功,3: 导出失败
	Desc         string                `gorm:"column:desc;not null;comment:导出内容描述" json:"desc"`                                     // 导出内容描述
	ErrorMessage string                `gorm:"column:error_message;not null;comment:导出失败的原因" json:"error_message"`                  // 导出失败的原因
	URL          string                `gorm:"column:url;not null;comment:导出文件的链接" json:"url"`                                      // 导出文件的链接
	Delete_      soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                           // 删除状态:0 未删除，1 已删除
}

// TableName PayExportTask's table name
func (*PayExportTask) TableName() string {
	return TableNamePayExportTask
}
