// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/datatypes"
	"gorm.io/plugin/soft_delete"
)

const TableNamePayBankaccountInfo = "pay_bankaccount_info"

// PayBankaccountInfo mapped from table <pay_bankaccount_info>
type PayBankaccountInfo struct {
	ID          int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`           // ID
	Bankcode    string                `gorm:"column:bankcode;not null;comment:银行代码" json:"bankcode"`                  // 银行代码
	Accountno   string                `gorm:"column:accountno;not null;comment:银行账号" json:"accountno"`                // 银行账号
	Accountname string                `gorm:"column:accountname;not null;comment:银行户名" json:"accountname"`            // 银行户名
	Accountinfo datatypes.JSON        `gorm:"column:accountinfo;comment:账号详情" json:"accountinfo"`                     // 账号详情
	Currency    string                `gorm:"column:currency;not null;comment:三位货币代码，人民币:CNY" json:"currency"`        // 三位货币代码，人民币:CNY
	Count_      int64                 `gorm:"column:count;not null;comment:交易笔数" json:"count"`                        // 交易笔数
	FailCount   int64                 `gorm:"column:fail_count;not null;comment:失败交易笔数" json:"fail_count"`            // 失败交易笔数
	FailIds     string                `gorm:"column:fail_ids;not null;comment:通道 id 标记，英文逗号拼接" json:"fail_ids"`       // 通道 id 标记，英文逗号拼接
	Failtext    string                `gorm:"column:failtext;comment:错误描述" json:"failtext"`                           // 错误描述
	Status      int64                 `gorm:"column:status;not null;default:1;comment:状态:1 正常，2 无效" json:"status"`    // 状态:1 正常，2 无效
	CreateTime  int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"` // 创建时间
	UpdateTime  int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"` // 更新时间
	Delete_     soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`              // 删除状态:0 未删除，1 已删除
}

// TableName PayBankaccountInfo's table name
func (*PayBankaccountInfo) TableName() string {
	return TableNamePayBankaccountInfo
}
