// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/datatypes"
	"gorm.io/plugin/soft_delete"
)

const TableNamePayMerchantNotify = "pay_merchant_notify"

// PayMerchantNotify mapped from table <pay_merchant_notify>
type PayMerchantNotify struct {
	ID              int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                  // ID
	OrderID         int64                 `gorm:"column:order_id;not null;comment:订单 id" json:"order_id"`                        // 订单 id
	MerchantID      int64                 `gorm:"column:merchant_id;not null;comment:商户 id" json:"merchant_id"`                  // 商户 id
	MerchantOrderNo string                `gorm:"column:merchant_order_no;not null;comment:商户订单号" json:"merchant_order_no"`      // 商户订单号
	NotifyURL       string                `gorm:"column:notify_url;comment:异步回调 url" json:"notify_url"`                          // 异步回调 url
	NotifyCount     int64                 `gorm:"column:notify_count;not null;comment:通知次数" json:"notify_count"`                 // 通知次数
	Result          datatypes.JSON        `gorm:"column:result;comment:返回内容" json:"result"`                                      // 返回内容
	OrderType       int64                 `gorm:"column:order_type;not null;default:1;comment:订单类型:1 代收，2 代付" json:"order_type"` // 订单类型:1 代收，2 代付
	Status          int64                 `gorm:"column:status;not null;default:1;comment:状态:1 通知中，2 通知成功，3 通知失败" json:"status"` // 状态:1 通知中，2 通知成功，3 通知失败
	LastNotifyTime  int64                 `gorm:"column:last_notify_time;comment:最后一次通知时间" json:"last_notify_time"`              // 最后一次通知时间
	CreateTime      int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`        // 创建时间
	UpdateTime      int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"`        // 更新时间
	Delete_         soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                     // 删除状态:0 未删除，1 已删除
}

// TableName PayMerchantNotify's table name
func (*PayMerchantNotify) TableName() string {
	return TableNamePayMerchantNotify
}
