// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/datatypes"
	"gorm.io/plugin/soft_delete"
)

const TableNamePayInaccountInfo = "pay_inaccount_info"

// PayInaccountInfo mapped from table <pay_inaccount_info>
type PayInaccountInfo struct {
	ID          int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`           // ID
	MerchantID  int64                 `gorm:"column:merchant_id;not null;comment:商户 id" json:"merchant_id"`           // 商户 id
	OrderNo     string                `gorm:"column:order_no;not null;comment:交易订单号" json:"order_no"`                 // 交易订单号
	Bankcode    string                `gorm:"column:bankcode;not null;comment:银行代码" json:"bankcode"`                  // 银行代码
	Accountno   string                `gorm:"column:accountno;not null;comment:银行账号" json:"accountno"`                // 银行账号
	Accountname string                `gorm:"column:accountname;not null;comment:银行户名" json:"accountname"`            // 银行户名
	Accountinfo datatypes.JSON        `gorm:"column:accountinfo;comment:账号详情" json:"accountinfo"`                     // 账号详情
	Currency    string                `gorm:"column:currency;not null;comment:三位货币代码，人民币:CNY" json:"currency"`        // 三位货币代码，人民币:CNY
	CreateTime  int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"` // 创建时间
	UpdateTime  int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"` // 更新时间
	Delete_     soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`              // 删除状态:0 未删除，1 已删除
}

// TableName PayInaccountInfo's table name
func (*PayInaccountInfo) TableName() string {
	return TableNamePayInaccountInfo
}
