// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNamePayMerchantTag = "pay_merchant_tags"

// PayMerchantTag mapped from table <pay_merchant_tags>
type PayMerchantTag struct {
	ID         int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`           // ID
	MerchantID int64                 `gorm:"column:merchant_id;not null;comment:商户 id" json:"merchant_id"`           // 商户 id
	TagID      int64                 `gorm:"column:tag_id;not null;comment:标签 id" json:"tag_id"`                     // 标签 id
	CreateTime int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"` // 创建时间
	UpdateTime int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"` // 更新时间
	Delete_    soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态：0 未删除，1 已删除" json:"-"`              // 删除状态：0 未删除，1 已删除
}

// TableName PayMerchantTag's table name
func (*PayMerchantTag) TableName() string {
	return TableNamePayMerchantTag
}
