// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNamePayMerchantAccount = "pay_merchant_account"

// PayMerchantAccount mapped from table <pay_merchant_account>
type PayMerchantAccount struct {
	ID         int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`               // ID
	MerchantID int64                 `gorm:"column:merchant_id;not null;comment:商户 id" json:"merchant_id"`               // 商户 id
	Currency   string                `gorm:"column:currency;not null;comment:货币代码：三字母大写" json:"currency"`                // 货币代码：三字母大写
	Balance    float64               `gorm:"column:balance;not null;default:0.0000;comment:可用余额" json:"balance"`         // 可用余额
	Deposit    float64               `gorm:"column:deposit;not null;default:0.0000;comment:代付余额" json:"deposit"`         // 代付余额
	Frozen     float64               `gorm:"column:frozen;not null;default:0.0000;comment:冻结余额" json:"frozen"`           // 冻结余额
	Profit     float64               `gorm:"column:profit;not null;default:0.0000;comment:收益余额" json:"profit"`           // 收益余额
	UsdRate    float64               `gorm:"column:usd_rate;not null;default:0.000000;comment:usd 交换汇率" json:"usd_rate"` // usd 交换汇率
	CreateTime int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`     // 创建时间
	UpdateTime int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"`     // 更新时间
	Delete_    soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                  // 删除状态:0 未删除，1 已删除
}

// TableName PayMerchantAccount's table name
func (*PayMerchantAccount) TableName() string {
	return TableNamePayMerchantAccount
}
