// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNamePaySystemAccount = "pay_system_account"

// PaySystemAccount mapped from table <pay_system_account>
type PaySystemAccount struct {
	ID               int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                       // ID
	Currency         string                `gorm:"column:currency;not null;comment:货币代码：三字母大写" json:"currency"`                        // 货币代码：三字母大写
	ExchangeCurrency string                `gorm:"column:exchange_currency;not null;comment:换汇货币代码：三字母大写" json:"exchange_currency"`    // 换汇货币代码：三字母大写
	ExchangeRate     float64               `gorm:"column:exchange_rate;not null;default:0.000000;comment:换汇平均汇率" json:"exchange_rate"` // 换汇平均汇率
	Balance          float64               `gorm:"column:balance;not null;default:0.0000;comment:余额" json:"balance"`                   // 余额
	Frozen           float64               `gorm:"column:frozen;not null;default:0.0000;comment:冻结余额" json:"frozen"`                   // 冻结余额
	CreateTime       int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`             // 创建时间
	UpdateTime       int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"`             // 更新时间
	Delete_          soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                          // 删除状态:0 未删除，1 已删除
}

// TableName PaySystemAccount's table name
func (*PaySystemAccount) TableName() string {
	return TableNamePaySystemAccount
}
