// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNamePayAgentCharge = "pay_agent_charge"

// PayAgentCharge mapped from table <pay_agent_charge>
type PayAgentCharge struct {
	ID                   int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                                               // ID
	AgentID              int64                 `gorm:"column:agent_id;not null;comment:代理 id" json:"agent_id"`                                                     // 代理 id
	PaymentServiceCharge float64               `gorm:"column:payment_service_charge;not null;default:0.00;comment:代理平台代收交易服务费 (单笔)" json:"payment_service_charge"` // 代理平台代收交易服务费 (单笔)
	PaymentTradeRate     float64               `gorm:"column:payment_trade_rate;not null;default:0.000000;comment:代理平台代收交易费率" json:"payment_trade_rate"`           // 代理平台代收交易费率
	PayoutServiceCharge  float64               `gorm:"column:payout_service_charge;not null;default:0.00;comment:代理平台代付交易服务费 (单笔)" json:"payout_service_charge"`   // 代理平台代付交易服务费 (单笔)
	PayoutTradeRate      float64               `gorm:"column:payout_trade_rate;not null;default:0.000000;comment:代理平台代付交易费率" json:"payout_trade_rate"`             // 代理平台代付交易费率
	CreateTime           int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`                                     // 创建时间
	UpdateTime           int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"`                                     // 更新时间
	Delete_              soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                                                  // 删除状态:0 未删除，1 已删除
}

// TableName PayAgentCharge's table name
func (*PayAgentCharge) TableName() string {
	return TableNamePayAgentCharge
}
