// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNamePaySystemAccountChange = "pay_system_account_change"

// PaySystemAccountChange mapped from table <pay_system_account_change>
type PaySystemAccountChange struct {
	ID                  int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                                          // ID
	Currency            string                `gorm:"column:currency;not null;comment:货币代码：三字母大写" json:"currency"`                                           // 货币代码：三字母大写
	Balance             float64               `gorm:"column:balance;not null;default:0.0000;comment:可用余额快照" json:"balance"`                                  // 可用余额快照
	Frozen              float64               `gorm:"column:frozen;not null;default:0.00;comment:冻结快照" json:"frozen"`                                        // 冻结快照
	Amount              float64               `gorm:"column:amount;not null;default:0.0000;comment:变动金额" json:"amount"`                                      // 变动金额
	ExchangeAmount      float64               `gorm:"column:exchange_amount;not null;default:0.00;comment:换汇金额" json:"exchange_amount"`                      // 换汇金额
	ExchangeCurrency    string                `gorm:"column:exchange_currency;not null;comment:换汇货币代码：三字母大写" json:"exchange_currency"`                       // 换汇货币代码：三字母大写
	ExchangeRate        float64               `gorm:"column:exchange_rate;not null;default:0.000000;comment:换汇汇率" json:"exchange_rate"`                      // 换汇汇率
	AccountExchangeRate float64               `gorm:"column:account_exchange_rate;not null;default:0.000000;comment:变动前账户平均汇率" json:"account_exchange_rate"` // 变动前账户平均汇率
	Source              int64                 `gorm:"column:source;not null;default:3;comment:变动来源：1 充值，2 提现，3 其它" json:"source"`                            // 变动来源：1 充值，2 提现，3 其它
	Way                 int64                 `gorm:"column:way;not null;default:1;comment:变动方向：1 增加，2 减少" json:"way"`                                       // 变动方向：1 增加，2 减少
	Status              int64                 `gorm:"column:status;not null;default:1;comment:状态：1 冻结，2 已入账，3 已撤销" json:"status"`                            // 状态：1 冻结，2 已入账，3 已撤销
	OrderNo             string                `gorm:"column:order_no;not null;comment:关联系统订单号" json:"order_no"`                                              // 关联系统订单号
	Remark              string                `gorm:"column:remark;not null;comment:备注" json:"remark"`                                                       // 备注
	CreateTime          int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`                                // 创建时间
	UpdateTime          int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"`                                // 更新时间
	Delete_             soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                                             // 删除状态:0 未删除，1 已删除
}

// TableName PaySystemAccountChange's table name
func (*PaySystemAccountChange) TableName() string {
	return TableNamePaySystemAccountChange
}
