// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/datatypes"
	"gorm.io/plugin/soft_delete"
)

const TableNamePayChannelBankcard = "pay_channel_bankcard"

// PayChannelBankcard mapped from table <pay_channel_bankcard>
type PayChannelBankcard struct {
	ID          int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`             // ID
	SupplierID  int64                 `gorm:"column:supplier_id;not null;comment:供应商 id" json:"supplier_id"`            // 供应商 id
	AccountName string                `gorm:"column:account_name;not null;comment:持卡人姓名" json:"account_name"`           // 持卡人姓名
	AccountNo   string                `gorm:"column:account_no;not null;comment:卡号" json:"account_no"`                  // 卡号
	BankName    string                `gorm:"column:bank_name;not null;comment:银行名称" json:"bank_name"`                  // 银行名称
	BankBranch  string                `gorm:"column:bank_branch;not null;comment:支行" json:"bank_branch"`                // 支行
	Province    string                `gorm:"column:province;comment:省" json:"province"`                                // 省
	City        string                `gorm:"column:city;not null;comment:市" json:"city"`                               // 市
	Extra       datatypes.JSON        `gorm:"column:extra;comment:自定义扩展信息" json:"extra"`                                // 自定义扩展信息
	Status      int64                 `gorm:"column:status;not null;default:1;comment:状态:1 启用，2 关闭，3 异常" json:"status"` // 状态:1 启用，2 关闭，3 异常
	Remark      string                `gorm:"column:remark;not null;comment:备注" json:"remark"`                          // 备注
	Weight      int64                 `gorm:"column:weight;not null;comment:权重值" json:"weight"`                         // 权重值
	DeviceID    string                `gorm:"column:device_id;not null;comment:监控设备标记" json:"device_id"`                // 监控设备标记
	CreateTime  int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`   // 创建时间
	UpdateTime  int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"`   // 更新时间
	Delete_     soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                // 删除状态:0 未删除，1 已删除
}

// TableName PayChannelBankcard's table name
func (*PayChannelBankcard) TableName() string {
	return TableNamePayChannelBankcard
}
