// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNamePayProductAccountCharge = "pay_product_account_charge"

// PayProductAccountCharge mapped from table <pay_product_account_charge>
type PayProductAccountCharge struct {
	ID                      int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                                                // ID
	PayProductAccountID     int64                 `gorm:"column:pay_product_account_id;not null;comment:子账号 id" json:"pay_product_account_id"`                         // 子账号 id
	PaymentServiceCharge    float64               `gorm:"column:payment_service_charge;not null;default:0.00;comment:通道代收交易服务费 (单笔)" json:"payment_service_charge"`    // 通道代收交易服务费 (单笔)
	PaymentMinServiceCharge float64               `gorm:"column:payment_min_service_charge;not null;default:0.00;comment:通道代收最低服务费" json:"payment_min_service_charge"` // 通道代收最低服务费
	PaymentMaxServiceCharge float64               `gorm:"column:payment_max_service_charge;not null;default:0.00;comment:通道代收最高服务费" json:"payment_max_service_charge"` // 通道代收最高服务费
	PaymentTradeRate        float64               `gorm:"column:payment_trade_rate;not null;default:0.000000;comment:通道代收交易费率" json:"payment_trade_rate"`              // 通道代收交易费率
	PayoutServiceCharge     float64               `gorm:"column:payout_service_charge;not null;default:0.00;comment:通道代付交易服务费 (单笔)" json:"payout_service_charge"`      // 通道代付交易服务费 (单笔)
	PayoutMinServiceCharge  float64               `gorm:"column:payout_min_service_charge;not null;default:0.00;comment:通道代付最低服务费" json:"payout_min_service_charge"`   // 通道代付最低服务费
	PayoutMaxServiceCharge  float64               `gorm:"column:payout_max_service_charge;not null;default:0.00;comment:通道代付最高服务费" json:"payout_max_service_charge"`   // 通道代付最高服务费
	PayoutTradeRate         float64               `gorm:"column:payout_trade_rate;not null;default:0.000000;comment:通道代付交易费率" json:"payout_trade_rate"`                // 通道代付交易费率
	CreateTime              int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`                                      // 创建时间
	UpdateTime              int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"`                                      // 更新时间
	Delete_                 soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                                                   // 删除状态:0 未删除，1 已删除
}

// TableName PayProductAccountCharge's table name
func (*PayProductAccountCharge) TableName() string {
	return TableNamePayProductAccountCharge
}
