// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNamePayMerchantAccountSnapshot = "pay_merchant_account_snapshot"

// PayMerchantAccountSnapshot mapped from table <pay_merchant_account_snapshot>
type PayMerchantAccountSnapshot struct {
	ID         int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`           // ID
	MerchantID int64                 `gorm:"column:merchant_id;not null;comment:商户 id" json:"merchant_id"`           // 商户 id
	Currency   string                `gorm:"column:currency;not null;comment:货币代码：三字母大写" json:"currency"`            // 货币代码：三字母大写
	Balance    float64               `gorm:"column:balance;not null;default:0.00;comment:可用余额" json:"balance"`       // 可用余额
	Deposit    float64               `gorm:"column:deposit;not null;default:0.00;comment:代付余额" json:"deposit"`       // 代付余额
	Frozen     float64               `gorm:"column:frozen;not null;default:0.00;comment:冻结余额" json:"frozen"`         // 冻结余额
	Profit     float64               `gorm:"column:profit;not null;default:0.00;comment:收益余额" json:"profit"`         // 收益余额
	Date       string                `gorm:"column:date;not null;comment:快照本地化日期" json:"date"`                       // 快照本地化日期
	CreateTime int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"` // 创建时间
	UpdateTime int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"` // 更新时间
	Delete_    soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`              // 删除状态:0 未删除，1 已删除
}

// TableName PayMerchantAccountSnapshot's table name
func (*PayMerchantAccountSnapshot) TableName() string {
	return TableNamePayMerchantAccountSnapshot
}
