// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNamePayProduct = "pay_product"

// PayProduct mapped from table <pay_product>
type PayProduct struct {
	ID         int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`           // ID
	Name       string                `gorm:"column:name;not null;comment:产品名称" json:"name"`                          // 产品名称
	Code       string                `gorm:"column:code;not null;comment:产品编码" json:"code"`                          // 产品编码
	Type       int64                 `gorm:"column:type;not null;default:1;comment:类型:1 代收，2 代付" json:"type"`        // 类型:1 代收，2 代付
	Params     string                `gorm:"column:params;not null;comment:接口配置定义描述，json 字符串" json:"params"`         // 接口配置定义描述，json 字符串
	Source     int64                 `gorm:"column:source;not null;default:1;comment:来源:1 系统，2 供应商" json:"source"`   // 来源:1 系统，2 供应商
	Tags       string                `gorm:"column:tags;not null;comment:标签，多个用英文逗号分隔" json:"tags"`                  // 标签，多个用英文逗号分隔
	Status     int64                 `gorm:"column:status;not null;default:1;comment:状态:1 启用，2 关闭" json:"status"`    // 状态:1 启用，2 关闭
	CreateTime int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"` // 创建时间
	UpdateTime int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"` // 更新时间
	Delete_    soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`              // 删除状态:0 未删除，1 已删除
}

// TableName PayProduct's table name
func (*PayProduct) TableName() string {
	return TableNamePayProduct
}
