// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/datatypes"
	"gorm.io/plugin/soft_delete"
)

const TableNamePayOutaccount = "pay_outaccount"

// PayOutaccount mapped from table <pay_outaccount>
type PayOutaccount struct {
	ID          int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`           // ID
	Bankcode    string                `gorm:"column:bankcode;not null;comment:银行代码" json:"bankcode"`                  // 银行代码
	Accountno   string                `gorm:"column:accountno;not null;comment:银行账号" json:"accountno"`                // 银行账号
	Accountname string                `gorm:"column:accountname;not null;comment:银行户名" json:"accountname"`            // 银行户名
	Accountinfo datatypes.JSON        `gorm:"column:accountinfo;comment:账号详情" json:"accountinfo"`                     // 账号详情
	Currency    string                `gorm:"column:currency;not null;comment:三位货币代码，人民币:CNY" json:"currency"`        // 三位货币代码，人民币:CNY
	Status      int64                 `gorm:"column:status;not null;default:1;comment:状态:1 正常，2 无效" json:"status"`    // 状态:1 正常，2 无效
	Remark      string                `gorm:"column:remark;not null;comment:备注" json:"remark"`                        // 备注
	CreateTime  int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"` // 创建时间
	UpdateTime  int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"` // 更新时间
	Delete_     soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`              // 删除状态:0 未删除，1 已删除
}

// TableName PayOutaccount's table name
func (*PayOutaccount) TableName() string {
	return TableNamePayOutaccount
}
