// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNamePaySupplierRule = "pay_supplier_rule"

// PaySupplierRule mapped from table <pay_supplier_rule>
type PaySupplierRule struct {
	ID         int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`           // ID
	Pid        int64                 `gorm:"column:pid;comment:父 id" json:"pid"`                                     // 父 id
	Name       string                `gorm:"column:name;not null;comment:名称" json:"name"`                            // 名称
	Icon       string                `gorm:"column:icon;not null;comment:图标" json:"icon"`                            // 图标
	URL        string                `gorm:"column:url;not null;comment:路由地址 (页面或外链)" json:"url"`                    // 路由地址 (页面或外链)
	Code       string                `gorm:"column:code;not null;comment:权限标识码" json:"code"`                         // 权限标识码
	Type       int64                 `gorm:"column:type;not null;default:1;comment:类型:1 目录，2 菜单，3 按钮" json:"type"`   // 类型:1 目录，2 菜单，3 按钮
	LinkStatus int64                 `gorm:"column:link_status;not null;comment:外链状态:1 外链，0 内部" json:"link_status"`  // 外链状态:1 外链，0 内部
	HideStatus int64                 `gorm:"column:hide_status;not null;comment:隐藏状态:1 隐藏，0 展示" json:"hide_status"`  // 隐藏状态:1 隐藏，0 展示
	Sort       int64                 `gorm:"column:sort;not null;comment:自然数排序值" json:"sort"`                        // 自然数排序值
	Status     int64                 `gorm:"column:status;not null;default:1;comment:状态:1 启用，0 禁用" json:"status"`    // 状态:1 启用，0 禁用
	Remark     string                `gorm:"column:remark;not null;comment:备注" json:"remark"`                        // 备注
	CreateTime int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"` // 创建时间
	UpdateTime int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"` // 更新时间
	Delete_    soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`              // 删除状态:0 未删除，1 已删除
}

// TableName PaySupplierRule's table name
func (*PaySupplierRule) TableName() string {
	return TableNamePaySupplierRule
}
