// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNamePayProductQueueConfig = "pay_product_queue_config"

// PayProductQueueConfig mapped from table <pay_product_queue_config>
type PayProductQueueConfig struct {
	ID              int64                 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreateTime      int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`                            // Create Time | 创建日期
	UpdateTime      int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"`                            // Update Time | 修改日期
	Delete_         soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                                         // 删除状态:0 未删除，1 已删除
	MqQueueConfigID int64                 `gorm:"column:mq_queue_config_id;not null;comment:MQ Queue ID" json:"mq_queue_config_id"`                  // MQ Queue ID
	PayProductCode  string                `gorm:"column:pay_product_code;not null;comment:PayProduct Code | 支付产品代码（上游银行代码）" json:"pay_product_code"` // PayProduct Code | 支付产品代码（上游银行代码）
}

// TableName PayProductQueueConfig's table name
func (*PayProductQueueConfig) TableName() string {
	return TableNamePayProductQueueConfig
}
