// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNamePayComplaintOrder = "pay_complaint_order"

// PayComplaintOrder mapped from table <pay_complaint_order>
type PayComplaintOrder struct {
	ID                    int64                 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreateTime            int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`                                       // 创建日期
	UpdateTime            int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"`                                       // 修改日期
	OrderCreateTime       int64                 `gorm:"column:order_create_time;not null;comment:订单创建日期" json:"order_create_time"`                                    // 订单创建日期
	ComplaintTime         int64                 `gorm:"column:complaint_time;not null;comment:投诉时间" json:"complaint_time"`                                            // 投诉时间
	MerchantEndTime       int64                 `gorm:"column:merchant_end_time;not null;comment:商户截止时间" json:"merchant_end_time"`                                    // 商户截止时间
	BankEndTime           int64                 `gorm:"column:bank_end_time;not null;comment:银行截止时间" json:"bank_end_time"`                                            // 银行截止时间
	PayerName             string                `gorm:"column:payer_name;not null;comment:付款人姓名" json:"payer_name"`                                                   // 付款人姓名
	OrderNo               string                `gorm:"column:order_no;not null;comment:交易订单号" json:"order_no"`                                                       // 交易订单号
	MerchantOrderNo       string                `gorm:"column:merchant_order_no;not null;comment:商户订单号" json:"merchant_order_no"`                                     // 商户订单号
	ChannelOrderNo        string                `gorm:"column:channel_order_no;not null;comment:渠道订单号" json:"channel_order_no"`                                       // 渠道订单号
	ChannelTradeNo        string                `gorm:"column:channel_trade_no;not null;comment:渠道用户交易号" json:"channel_trade_no"`                                     // 渠道用户交易号
	Amount                float64               `gorm:"column:amount;not null;default:0.00;comment:交易金额" json:"amount"`                                               // 交易金额
	Currency              string                `gorm:"column:currency;not null;default:CNY;comment:三位货币代码，人民币:CNY" json:"currency"`                                  // 三位货币代码，人民币:CNY
	MerchantID            int64                 `gorm:"column:merchant_id;not null;comment:商户 id" json:"merchant_id"`                                                 // 商户 id
	ProductID             int64                 `gorm:"column:product_id;not null;comment:产品 id" json:"product_id"`                                                   // 产品 id
	ProductName           string                `gorm:"column:product_name;not null;comment:产品名称" json:"product_name"`                                                // 产品名称
	Status                int64                 `gorm:"column:status;not null;comment:1:未接收（商户反馈）、2:已接收（商户反馈）、3:已驳回（商户反馈）、4:已提交（银行）、5:已退款" json:"status"`             // 1:未接收（商户反馈）、2:已接收（商户反馈）、3:已驳回（商户反馈）、4:已提交（银行）、5:已退款
	FreezeStatus          int64                 `gorm:"column:freeze_status;not null;comment:1:未冻结、2:已冻结、3:冻结失败、4:已解冻、5:已退款" json:"freeze_status"`                    // 1:未冻结、2:已冻结、3:冻结失败、4:已解冻、5:已退款
	Reason                string                `gorm:"column:reason;not null;comment:投诉原因" json:"reason"`                                                            // 投诉原因
	RefundReason          string                `gorm:"column:refund_reason;not null;comment:退款原因" json:"refund_reason"`                                              // 退款原因
	RejectReason          string                `gorm:"column:reject_reason;not null;comment:驳回商户提交原因" json:"reject_reason"`                                          // 驳回商户提交原因
	RechargeRecordImgUrls string                `gorm:"column:recharge_record_img_urls;not null;comment:商户提交的充值记录图片urls (最多3张，逗号隔开)" json:"recharge_record_img_urls"` // 商户提交的充值记录图片urls (最多3张，逗号隔开)
	WithdrawRecordImgUrls string                `gorm:"column:withdraw_record_img_urls;not null;comment:商户提交的提现记录图片urls (最多3张，逗号隔开)" json:"withdraw_record_img_urls"` // 商户提交的提现记录图片urls (最多3张，逗号隔开)
	GamesRecordImgUrls    string                `gorm:"column:games_record_img_urls;not null;comment:商户提交的游戏记录图片urls (最多3张，逗号隔开)" json:"games_record_img_urls"`       // 商户提交的游戏记录图片urls (最多3张，逗号隔开)
	GameUserUUID          string                `gorm:"column:game_user_uuid;not null;comment:商户的游戏用户 uuid" json:"game_user_uuid"`                                    // 商户的游戏用户 uuid
	MerchantIsRefund      int64                 `gorm:"column:merchant_is_refund;not null;comment:商户是否退还客户 | 1:退款、 2:不退款" json:"merchant_is_refund"`                  // 商户是否退还客户 | 1:退款、 2:不退款
	ReadPassword          string                `gorm:"column:read_password;not null;comment:商户查看密码" json:"read_password"`                                            // 商户查看密码
	Delete_               soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                                                    // 删除状态:0 未删除，1 已删除
	RegistrationImgUrls   string                `gorm:"column:registration_img_urls;not null;comment:玩家注册信息截图 urls (最多3张，逗号隔开)" json:"registration_img_urls"`         // 玩家注册信息截图 urls (最多3张，逗号隔开)
	Cpf                   string                `gorm:"column:cpf;not null;comment:投诉人的 CPF 号码" json:"cpf"`                                                           // 投诉人的 CPF 号码
}

// TableName PayComplaintOrder's table name
func (*PayComplaintOrder) TableName() string {
	return TableNamePayComplaintOrder
}
