// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePaymentOrderIndex = "payment_order_index"

// PaymentOrderIndex mapped from table <payment_order_index>
type PaymentOrderIndex struct {
	ID              int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`             // ID
	MerchantID      int64  `gorm:"column:merchant_id;not null;comment:商户 id" json:"merchant_id"`             // 商户 id
	MerchantOrderNo string `gorm:"column:merchant_order_no;not null;comment:商户订单号" json:"merchant_order_no"` // 商户订单号
}

// TableName PaymentOrderIndex's table name
func (*PaymentOrderIndex) TableName() string {
	return TableNamePaymentOrderIndex
}
