// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayoutOrderFinish = "payout_order_finish"

// PayoutOrderFinish mapped from table <payout_order_finish>
type PayoutOrderFinish struct {
	ID int64 `gorm:"column:id;primaryKey;comment:订单 ID" json:"id"` // 订单 ID
}

// TableName PayoutOrderFinish's table name
func (*PayoutOrderFinish) TableName() string {
	return TableNamePayoutOrderFinish
}
