// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNamePayoutOrderIndex = "payout_order_index"

// PayoutOrderIndex mapped from table <payout_order_index>
type PayoutOrderIndex struct {
	ID              int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`             // ID
	MerchantID      int64  `gorm:"column:merchant_id;not null;comment:商户 id" json:"merchant_id"`             // 商户 id
	MerchantOrderNo string `gorm:"column:merchant_order_no;not null;comment:商户订单号" json:"merchant_order_no"` // 商户订单号
}

// TableName PayoutOrderIndex's table name
func (*PayoutOrderIndex) TableName() string {
	return TableNamePayoutOrderIndex
}
