// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNameSysAPI = "sys_apis"

// SysAPI mapped from table <sys_apis>
type SysAPI struct {
	ID          int64                 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreateTime  int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`                                                                      // Create Time | 创建日期
	UpdateTime  int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"`                                                                      // Update Time | 修改日期
	Path        string                `gorm:"column:path;not null;comment:API path | API 路径" json:"path"`                                                                                  // API path | API 路径
	Description string                `gorm:"column:description;not null;comment:API description | API 描述" json:"description"`                                                             // API description | API 描述
	APIGroup    string                `gorm:"column:api_group;not null;comment:API group | API 分组" json:"api_group"`                                                                       // API group | API 分组
	Method      string                `gorm:"column:method;not null;default:POST;comment:HTTP method | HTTP 请求类型" json:"method"`                                                           // HTTP method | HTTP 请求类型
	IsRequired  int64                 `gorm:"column:is_required;not null;comment:Whether is required | 是否必选 1 可选 2 所有用户必选 3 manager 用户必选 4 merchant 用户必选 5 agent 用户必选" json:"is_required"` // Whether is required | 是否必选 1 可选 2 所有用户必选 3 manager 用户必选 4 merchant 用户必选 5 agent 用户必选
	Delete_     soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                                                                                   // 删除状态:0 未删除，1 已删除
}

// TableName SysAPI's table name
func (*SysAPI) TableName() string {
	return TableNameSysAPI
}
