// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import "gorm.io/plugin/soft_delete"

const TableNameSysRole = "sys_roles"

// SysRole mapped from table <sys_roles>
type SysRole struct {
	ID            int64                 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreateTime    int64                 `gorm:"column:create_time;type:bigint;autoCreateTime:milli" json:"create_time"`                                                    // Create Time | 创建日期
	UpdateTime    int64                 `gorm:"column:update_time;type:bigint;autoUpdateTime:milli" json:"update_time"`                                                    // Update Time | 修改日期
	Status        int64                 `gorm:"column:status;default:1;comment:Status 1 : normal 2 : ban | 状态 1 正常 2 禁用" json:"status"`                                    // Status 1 : normal 2 : ban | 状态 1 正常 2 禁用
	Name          string                `gorm:"column:name;not null;comment:Role name | 角色名" json:"name"`                                                                  // Role name | 角色名
	Code          string                `gorm:"column:code;not null;comment:Role code for permission control in front end | 角色码，用于前端权限控制" json:"code"`                     // Role code for permission control in front end | 角色码，用于前端权限控制
	DefaultRouter string                `gorm:"column:default_router;not null;default:dashboard;comment:Default menu : dashboard | 默认登录页面" json:"default_router"`          // Default menu : dashboard | 默认登录页面
	Remark        string                `gorm:"column:remark;not null;comment:Remark | 备注" json:"remark"`                                                                  // Remark | 备注
	Sort          int64                 `gorm:"column:sort;not null;comment:Order number | 排序编号" json:"sort"`                                                              // Order number | 排序编号
	Delete_       soft_delete.DeletedAt `gorm:"column:_delete;not null;comment:删除状态:0 未删除，1 已删除" json:"-"`                                                                 // 删除状态:0 未删除，1 已删除
	Type          int64                 `gorm:"column:type;not null;default:1;comment:角色类型 1: manager, 2: merchant, 3: agent" json:"type"`                                 // 角色类型 1: manager, 2: merchant, 3: agent
	MasterID      int64                 `gorm:"column:master_id;not null;comment:主账号ID，管理端创建的角色，此字段为0，其他端创建的角色，此字段为创建者ID。其他端设置角色时不能选中 master_id 为 0 的角色" json:"master_id"` // 主账号ID，管理端创建的角色，此字段为0，其他端创建的角色，此字段为创建者ID。其他端设置角色时不能选中 master_id 为 0 的角色
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
