// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserRole = "user_roles"

// UserRole mapped from table <user_roles>
type UserRole struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserType string `gorm:"column:user_type;not null;comment:User Type | 用户类型" json:"user_type"` // User Type | 用户类型
	UserID   int64  `gorm:"column:user_id;not null;comment:User Id | 用户 ID" json:"user_id"`      // User Id | 用户 ID
	RoleID   int64  `gorm:"column:role_id;not null" json:"role_id"`
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
